<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tacc.serviceOrder.Domain\Tacc.serviceOrder.Domain.csproj" />
    <ProjectReference Include="..\Tacc.serviceOrder.Intrastructure\Tacc.serviceOrder.Intrastructure.csproj" />
  </ItemGroup>

</Project>
